apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: hello-infra
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
     labels:
        app: jenkins
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80

